[package]
name = "use_yewdux"

version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yewdux = "0.8.2"
yew="0.19.3"